version: "3.4"
services:
  server:
    hostname: server
    build:
      context: .
      target: server
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - .:/srv
      - /sys/fs/cgroup:/sys/fs/cgroup:ro